// Universal / unambiguous holidays shared across many countries — safe to match generically.
module.exports.COMMON_DESCRIPTIONS = [
  [/new year'?s day/i, "The first day of the Gregorian calendar year, marked with fireworks, family gatherings, and a fresh start after the festive season."],
  [/day after new year/i, "An extra rest day tacked onto New Year's Day so celebrations can run into a second day without affecting the working week."],
  [/last day of the year/i, "An extra rest day added to close out the calendar year alongside New Year's celebrations."],
  [/good friday/i, "A Christian observance marking the crucifixion of Jesus Christ, held on the Friday before Easter Sunday."],
  [/easter monday/i, "The day after Easter Sunday, traditionally used to extend the Easter weekend into a four-day break."],
  [/easter sunday/i, "The most important date in the Christian calendar, celebrating the resurrection of Jesus Christ."],
  [/easter eve|holy saturday|sabado de gloria/i, "The final day of Holy Week, observed quietly between Good Friday and Easter Sunday."],
  [/maundy thursday|jueves santo|huwebes santo/i, "Commemorates the Last Supper and marks the start of the Easter Triduum in the Christian calendar."],
  [/whit monday|pentecost monday|day after ascension/i, "Falls the day after Pentecost, seven weeks after Easter, and is kept as an extra spring public holiday."],
  [/ascension/i, "A Christian feast held 40 days after Easter, commemorating the ascension of Jesus into heaven."],
  [/pentecost/i, "A Christian feast held 50 days after Easter, marking the descent of the Holy Spirit on the apostles."],
  [/corpus christi/i, "A Catholic feast honouring the Eucharist, celebrated 60 days after Easter Sunday."],
  [/all saints/i, "A Christian holy day honouring all saints, widely observed by visiting family graves and cemeteries."],
  [/all souls/i, "A day of remembrance for the deceased, traditionally marked with visits to cemeteries and family gatherings."],
  [/epiphany/i, "Marks the visit of the Three Wise Men to the infant Jesus and traditionally closes out the Christmas season."],
  [/assumption/i, "A Catholic feast celebrating the bodily assumption of the Virgin Mary into heaven."],
  [/immaculate conception/i, "A Catholic feast honouring the Virgin Mary, widely observed with Mass and family time."],
  [/christmas eve/i, "The evening before Christmas Day, typically the biggest family gathering of the year in many cultures."],
  [/christmas day/i, "The Christian celebration of the birth of Jesus Christ, and the biggest family holiday of the year across much of the world."],
  [/st\.? stephen|boxing day/i, "A traditional post-Christmas rest day, historically associated with giving to servants and the needy."],
];

// Country-specific overrides — matched by exact English `name` field first, before the common list.
// Keeps holidays that share a label across countries (e.g. "Family Day", "National Day",
// "Thanksgiving", "Women's Day") from bleeding into each other's descriptions.
module.exports.COUNTRY_OVERRIDES = {
  US: {
    "Martin Luther King, Jr. Day": "Honours the civil rights leader Dr. Martin Luther King Jr. and his legacy of nonviolent activism, observed on the third Monday of January.",
    "Lincoln's Birthday": "A regional observance of Abraham Lincoln's birthday, still a holiday in a handful of states.",
    "Presidents Day": "Originally honouring George Washington's birthday, now widely celebrated as a tribute to all U.S. presidents.",
    "Truman Day": "A Missouri state holiday marking the birthday of President Harry S. Truman.",
    "Memorial Day": "A solemn day honouring U.S. military personnel who died while serving in the armed forces.",
    "Juneteenth National Independence Day": "Commemorates the end of slavery in the United States, marking when the last enslaved people in Texas learned they were free in 1865.",
    "Independence Day": "Celebrates the adoption of the Declaration of Independence in 1776 with fireworks, parades, and barbecues nationwide.",
    "Labour Day": "Honours the American labour movement, held on the first Monday of September and marking the unofficial end of summer.",
    "Columbus Day": "Marks Christopher Columbus's arrival in the Americas in 1492; observed alongside or instead of Indigenous Peoples' Day in parts of the country.",
    "Indigenous Peoples' Day": "Honours the history and culture of Native American peoples, observed on the same date as Columbus Day in many states and cities.",
    "Veterans Day": "Honours all U.S. military veterans, distinct from Memorial Day which remembers those who died in service.",
    "Thanksgiving Day": "A harvest-themed holiday centred on family meals and giving thanks, traced back to a 1621 harvest feast in Plymouth.",
  },
  GB: {
    "2 January": "An additional Scottish bank holiday following New Year's Day, giving Scotland an extra day off that other UK nations don't get.",
    "Saint Patrick's Day": "A celebration of Irish culture marking the feast day of Ireland's patron saint, a public holiday in Northern Ireland.",
    "Early May Bank Holiday": "A UK-wide bank holiday held on the first Monday of May.",
    "Spring Bank Holiday": "A UK-wide bank holiday held on the last Monday of May.",
    "World Cup Bank Holiday": "A one-off bank holiday declared to mark a major national sporting occasion.",
    "Battle of the Boyne": "Commemorates a decisive 1690 battle between rival claimants to the British throne, observed as the Twelfth of July in Northern Ireland.",
    "Summer Bank Holiday": "A UK bank holiday marking the end of summer — held in late August in England, Wales and Northern Ireland, and early August in Scotland.",
    "Saint Andrew's Day": "The feast day of Scotland's patron saint, marked with cultural events across Scotland.",
  },
  AU: {
    "Australia Day": "Marks the 1788 arrival of the First Fleet at Sydney Cove, observed with citizenship ceremonies and community events nationwide.",
    "Labour Day": "A state-specific holiday honouring the eight-hour work day movement, held on different dates across Australian states.",
    "Canberra Day": "Marks the founding of Canberra, observed only in the Australian Capital Territory.",
    "Adelaide Cup Day": "A South Australian public holiday tied to the running of the Adelaide Cup horse race.",
    "Eight Hours Day": "Tasmania's name for Labour Day, commemorating the 19th-century campaign for an eight-hour working day.",
    "Easter Eve": "The Saturday of Easter weekend, a public holiday in several Australian states.",
    "Anzac Day": "Honours members of the Australian and New Zealand Army Corps who served and died in war, marked with dawn services nationwide.",
    "May Day": "The Northern Territory's name for its early-May Labour Day holiday.",
    "Reconciliation Day": "An ACT public holiday promoting reconciliation between Indigenous and non-Indigenous Australians.",
    "Western Australia Day": "Commemorates the founding of the Swan River Colony, marked only in Western Australia.",
    "King's Birthday": "An official celebration of the monarch's birthday, observed on a state-specific date rather than the actual birthday.",
    "Picnic Day": "A Northern Territory holiday traditionally used for community picnics and local shows.",
    "Friday before AFL Grand Final": "A Victorian public holiday added to mark the state's biggest sporting event of the year.",
    "Melbourne Cup": "A Victorian public holiday held for \"the race that stops a nation\", Australia's most famous horse race.",
  },
  CA: {
    "Family Day": "A provincial statutory holiday held in mid-February, known by different names across Canada's provinces.",
    "Louis Riel Day": "Manitoba's name for its mid-February Family Day, honouring Métis leader Louis Riel.",
    "Islander Day": "Prince Edward Island's name for its mid-February Family Day public holiday.",
    "Heritage Day": "A provincial civic holiday, held on different dates depending on the province.",
    "Saint Patrick's Day": "Observed as a public holiday in Newfoundland and Labrador, celebrating Irish heritage.",
    "Good Friday": "A Christian observance marking the crucifixion of Jesus Christ, a federal statutory holiday in Canada.",
    "Easter Monday": "A federal public-service holiday observed the day after Easter Sunday.",
    "Saint George's Day": "A regional Canadian holiday marking the feast of England's patron saint, observed in Newfoundland and Labrador.",
    "National Patriots' Day": "Québec's name for Victoria Day, commemorating the province's patriots and francophone heritage.",
    "Victoria Day": "Honours Queen Victoria's birthday and traditionally marks the unofficial start of summer in most of Canada.",
    "National Aboriginal Day": "A day recognising the heritage, diversity, and contributions of Indigenous peoples in Canada.",
    "Discovery Day": "A provincial holiday marking a historic regional discovery, observed in Yukon and Newfoundland and Labrador.",
    "National Holiday": "Québec's Fête nationale, celebrating the province's francophone culture and identity on Saint-Jean-Baptiste Day.",
    "Canada Day": "Celebrates the anniversary of Canadian Confederation in 1867 with fireworks and community events nationwide.",
    "Orangemen's Day": "A Newfoundland provincial holiday with roots in the Orange Order's July marches.",
    "Civic Holiday": "A federal-employee civic holiday observed on the first Monday of August under different local names by province.",
    "British Columbia Day": "British Columbia's name for the first-Monday-in-August civic holiday.",
    "New Brunswick Day": "New Brunswick's name for the first-Monday-in-August civic holiday.",
    "Natal Day": "Nova Scotia's name for the first-Monday-in-August civic holiday.",
    "Saskatchewan Day": "Saskatchewan's name for the first-Monday-in-August civic holiday.",
    "Gold Cup Parade Day": "A local Prince Edward Island holiday tied to the Gold Cup Parade festival in Charlottetown.",
    "Labour Day": "Honours the Canadian labour movement, held on the first Monday of September.",
    "National Day for Truth and Reconciliation": "A day of reflection on the legacy of residential schools and reconciliation with Indigenous communities.",
    "Thanksgiving": "A Canadian harvest holiday held on the second Monday of October, centred on family meals.",
    "Armistice Day": "Commemorates the end of the First World War, observed alongside Remembrance Day.",
    "Remembrance Day": "Honours Canadian military veterans and war dead with a moment of silence at 11am on 11 November.",
    "Christmas Day": "The Christian celebration of the birth of Jesus Christ, and the biggest family holiday of the year in Canada.",
    "Boxing Day": "A traditional post-Christmas rest day, now widely associated with retail sales across Canada.",
  },
  DE: {
    "International Women's Day": "A global day recognising women's achievements and advocating for gender equality, a public holiday only in Berlin.",
    "Easter Sunday": "The most important date in the Christian calendar, observed as a public-service holiday in Germany.",
    "Labour Day": "Honours workers and the labour movement, held nationwide on 1 May.",
    "Pentecost": "A Christian feast held 50 days after Easter, marking the descent of the Holy Spirit.",
    "World Children's Day": "A German regional observance promoting children's rights, marked as a public holiday only in Thuringia.",
    "German Unity Day": "Commemorates German reunification in 1990, when East and West Germany became one country again.",
    "Reformation Day": "Commemorates the start of the Protestant Reformation in 1517, a holiday mainly in Germany's Protestant-majority states.",
    "Repentance and Prayer Day": "A Protestant day of prayer and reflection, now a public holiday only in the German state of Saxony.",
  },
  FR: {
    "Labour Day": "Honours workers and the labour movement, held nationwide on 1 May.",
    "Victory in Europe Day": "Commemorates the Allied victory in Europe and the end of the Second World War in 1945.",
    "Ascension Day": "A Christian feast held 40 days after Easter, commemorating the ascension of Jesus into heaven.",
    "Bastille Day": "France's national day, commemorating the storming of the Bastille prison in 1789 and marked with military parades on the Champs-Élysées.",
    "Armistice Day": "Marks the armistice that ended the First World War on 11 November 1918.",
  },
  JP: {
    "Coming of Age Day": "Celebrates young people who reached the age of majority (18) during the past year, marked with ceremonies and formal dress.",
    "Foundation Day": "Commemorates the legendary founding of Japan under its first Emperor.",
    "The Emperor's Birthday": "Celebrates the birthday of the reigning Emperor.",
    "Vernal Equinox Day": "A traditional seasonal holiday for visiting family graves and appreciating nature, tied to the spring equinox.",
    "Shōwa Day": "Reflects on the Shōwa era and honours the birthday of former Emperor Shōwa.",
    "Constitution Memorial Day": "Commemorates the 1947 enactment of Japan's post-war constitution.",
    "Greenery Day": "A day for appreciating nature, originally tied to the Shōwa Emperor's love of plants.",
    "Children's Day": "A day celebrating children's happiness and personalities, part of Japan's Golden Week holidays.",
    "Marine Day": "Gives thanks to the ocean for the prosperity it brings to an island nation.",
    "Mountain Day": "A public holiday for appreciating mountains, one of Japan's newest national holidays.",
    "Respect for the Aged Day": "Honours elderly citizens and celebrates longevity.",
    "Autumnal Equinox Day": "A traditional seasonal holiday for visiting family graves, tied to the autumn equinox.",
    "Sports Day": "Commemorates the opening of the 1964 Tokyo Olympics and promotes sport and an active lifestyle.",
    "Culture Day": "A day promoting culture, the arts, and academic achievement, with award ceremonies held nationwide.",
    "Labour Thanksgiving Day": "A day for commemorating labour and giving one another thanks, rooted in ancient harvest festivals.",
  },
  BR: {
    "Carnival": "A pre-Lent festival famous for parades, music, and costumes, with Rio de Janeiro's celebrations among the world's largest.",
    "Tiradentes": "Honours Joaquim José da Silva Xavier, a martyr of Brazil's independence movement, executed in 1792.",
    "Labour Day": "Honours workers and the labour movement, held nationwide on 1 May.",
    "Corpus Christi": "A Catholic feast honouring the Eucharist, widely observed with processions across Brazil.",
    "Constitutionalist Revolution of 1932": "A São Paulo state holiday commemorating a 1932 uprising against the federal government.",
    "Independence Day": "Commemorates Brazil's declaration of independence from Portugal in 1822.",
    "Our Lady of Aparecida": "Honours Brazil's patron saint, Our Lady of Aparecida, with pilgrimages to her national shrine.",
    "All Souls' Day": "A day of remembrance for the deceased, marked with visits to cemeteries across Brazil.",
    "Republic Proclamation Day": "Marks the 1889 proclamation of the Brazilian republic, ending the monarchy.",
    "Black Awareness Day": "A day recognising Afro-Brazilian history and culture, and confronting the legacy of slavery.",
  },
  MX: {
    "Constitution Day": "Marks the anniversary of the 1917 Mexican Constitution, observed on the first Monday of February.",
    "Benito Juárez's birthday": "Honours the birthday of Benito Juárez, one of Mexico's most celebrated former presidents.",
    "Labour Day": "Honours workers and the labour movement, held nationwide on 1 May.",
    "Independence Day": "Commemorates the start of Mexico's War of Independence against Spain in 1810, celebrated with El Grito ceremonies.",
    "Revolution Day": "Commemorates the start of the Mexican Revolution in 1910, observed on the third Monday of November.",
  },
  ES: {
    "Epiphany": "Marks the visit of the Three Wise Men to the infant Jesus, a major gift-giving day in Spain.",
    "Day of Andalucía": "A regional public holiday celebrating the autonomous community of Andalucía.",
    "Day of the Balearic Islands": "A regional public holiday celebrating the Balearic Islands.",
    "Maundy Thursday": "Commemorates the Last Supper and marks the start of the Easter Triduum, a holiday in most Spanish regions.",
    "Easter Monday": "Observed as a regional public holiday in several Spanish autonomous communities, including Catalonia.",
    "Castile and León Day": "A regional public holiday celebrating the autonomous community of Castile and León.",
    "Day of Aragón": "A regional public holiday celebrating the autonomous community of Aragón, tied to the feast of Saint George.",
    "Labour Day": "Honours workers and the labour movement, held nationwide on 1 May.",
    "Day of Madrid": "A regional public holiday celebrating the Community of Madrid.",
    "Galician Literature Day": "A Galician regional holiday celebrating the region's literary heritage.",
    "Day of the Canary Islands": "A regional public holiday celebrating the Canary Islands.",
    "Day of Castilla-La Mancha": "A regional public holiday celebrating the autonomous community of Castilla-La Mancha.",
    "Corpus Christi": "A Catholic feast honouring the Eucharist, observed as a regional holiday in parts of Spain.",
    "Day of La Rioja": "A regional public holiday celebrating the autonomous community of La Rioja.",
    "Day of Murcia": "A regional public holiday celebrating the Region of Murcia.",
    "St. John's Day": "A midsummer feast celebrated with bonfires, observed as a regional holiday in Catalonia.",
    "Santiago Apóstol": "The feast of Saint James, patron saint of Spain, observed as a regional holiday in Galicia.",
    "Day of the Cantabrian Institutions": "A regional public holiday celebrating the autonomous community of Cantabria.",
    "Assumption": "A Catholic feast celebrating the bodily assumption of the Virgin Mary into heaven.",
    "Day of Asturias": "A regional public holiday celebrating the Principality of Asturias.",
    "Day of Extremadura": "A regional public holiday celebrating the autonomous community of Extremadura.",
    "National Day of Catalonia": "Catalonia's own national day (the Diada), commemorating the fall of Barcelona in 1714.",
    "Feast of Our Lady of Bien Aparecida": "A Cantabrian regional holiday honouring the patron saint of Cantabria.",
    "Day of the Valencian Community": "A regional public holiday celebrating the Valencian Community.",
    "National Day of Spain": "Spain's national day, commemorating Columbus's arrival in the Americas in 1492 and marked with a military parade in Madrid.",
    "All Saints Day": "A Christian holy day honouring all saints, widely observed by visiting family graves and cemeteries.",
    "Constitution Day": "Marks the anniversary of the 1978 Spanish Constitution that established the current democracy.",
    "Immaculate Conception": "A Catholic feast honouring the Virgin Mary, widely observed with Mass and family time.",
  },
  IT: {
    "Epiphany": "Marks the visit of the Three Wise Men to the infant Jesus, celebrated in Italy with the gift-giving figure of La Befana.",
    "Liberation Day": "Commemorates Italy's liberation from Nazi occupation and fascism at the end of the Second World War in 1945.",
    "International Workers Day": "Honours workers and the labour movement, held nationwide on 1 May.",
    "Republic Day": "Celebrates the 1946 referendum in which Italians voted to become a republic, ending the monarchy.",
    "Assumption Day": "Known in Italy as Ferragosto, a Catholic feast that doubles as the peak of the summer holiday season.",
    "St. Francis of Assisi's Day": "Honours Italy's patron saint, Saint Francis of Assisi.",
    "All Saints Day": "A Christian holy day honouring all saints, widely observed by visiting family graves and cemeteries.",
    "Immaculate Conception": "A Catholic feast honouring the Virgin Mary, widely observed with Mass and family time.",
  },
  NL: {
    "Good Friday": "A Christian observance marking the crucifixion of Jesus Christ, a public-service holiday in the Netherlands.",
    "Easter Sunday": "The most important date in the Christian calendar, celebrating the resurrection of Jesus Christ.",
    "Easter Monday": "The day after Easter Sunday, traditionally used to extend the Easter weekend.",
    "King's Day": "A nationwide street-party holiday celebrating the King's birthday, famous for open-air markets and orange-themed festivities.",
    "Liberation Day": "Commemorates the Netherlands' liberation from Nazi occupation in 1945, a full public holiday only once every five years.",
    "Ascension Day": "A Christian feast held 40 days after Easter, commemorating the ascension of Jesus into heaven.",
    "Pentecost": "A Christian feast held 50 days after Easter, marking the descent of the Holy Spirit.",
    "Whit Monday": "Falls the day after Pentecost and is kept as an extra spring public holiday in the Netherlands.",
    "Christmas Day": "The Christian celebration of the birth of Jesus Christ, and the biggest family holiday of the year.",
    "St. Stephen's Day": "The Netherlands' second Christmas Day, a traditional extra day of family time.",
  },
  NZ: {
    "New Year's Day": "The first day of the Gregorian calendar year, marked with fireworks and family gatherings.",
    "Day after New Year's Day": "An extra rest day tacked onto New Year's Day, giving New Zealanders two full days to celebrate.",
    "Wellington Anniversary Day": "A provincial holiday marking the founding of the Wellington region.",
    "Auckland Anniversary Day": "A provincial holiday marking the founding of the Auckland/Northland region.",
    "Nelson Anniversary Day": "A provincial holiday marking the founding of the Nelson region.",
    "Waitangi Day": "Commemorates the 1840 signing of the Treaty of Waitangi between the British Crown and Māori chiefs.",
    "Taranaki Anniversary Day": "A provincial holiday marking the founding of the Taranaki region.",
    "Otago Anniversary Day": "A provincial holiday marking the founding of the Otago region.",
    "Good Friday": "A Christian observance marking the crucifixion of Jesus Christ, a public holiday across New Zealand.",
    "Easter Monday": "The day after Easter Sunday, extending the Easter weekend into a four-day break.",
    "Southland Anniversary Day": "A provincial holiday marking the founding of the Southland region.",
    "Anzac Day": "Honours members of the Australian and New Zealand Army Corps who served and died in war, marked with dawn services nationwide.",
    "King's Birthday": "An official celebration of the monarch's birthday, observed on the first Monday of June.",
    "Matariki": "Marks the Māori New Year, signalled by the rise of the Matariki star cluster in the winter sky — New Zealand's newest public holiday.",
    "Canterbury (South) Anniversary Day": "A provincial holiday historically known as Dominion Day, marking the South Canterbury region.",
    "Hawke's Bay Anniversary Day": "A provincial holiday marking the founding of the Hawke's Bay region.",
    "Labour Day": "Commemorates the 19th-century campaign for an eight-hour working day, held on the fourth Monday of October.",
    "Marlborough Anniversary Day": "A provincial holiday marking the founding of the Marlborough region.",
    "Canterbury Anniversary Day": "A provincial holiday marking the founding of the Canterbury region.",
    "Chatham Islands Anniversary Day": "A provincial holiday marking the founding of the Chatham Islands.",
    "Westland Anniversary Day": "A provincial holiday marking the founding of the Westland region.",
    "Christmas Day": "The Christian celebration of the birth of Jesus Christ, the biggest family holiday of the year.",
    "Boxing Day": "A traditional post-Christmas rest day, popular for the start of the summer sales.",
  },
  SG: {
    "Chinese New Year": "The start of the lunar calendar year, celebrated with family reunions, red envelopes, and lion dances, observed over two days in Singapore.",
    "Hari Raya Puasa": "Marks the end of the Muslim fasting month of Ramadan, celebrated with prayers and family feasts.",
    "Good Friday": "A Christian observance marking the crucifixion of Jesus Christ, a public holiday in multicultural Singapore.",
    "Labour Day": "Honours workers and the labour movement, held nationwide on 1 May.",
    "Hari Raya Haji": "An Islamic festival of sacrifice, marked by communal prayers and charitable giving.",
    "Vesak Day": "Commemorates the birth, enlightenment, and passing of the Buddha.",
    "National Day": "Celebrates Singapore's independence in 1965 with a major parade and fireworks display.",
    "Deepavali": "The Hindu festival of lights, celebrating the victory of light over darkness with lamps and fireworks.",
    "Christmas Day": "The Christian celebration of the birth of Jesus Christ, marked with festive light displays along Orchard Road.",
  },
  ZA: {
    "Human Rights Day": "Commemorates the 1960 Sharpeville massacre and honours the human rights enshrined in South Africa's Constitution.",
    "Family Day": "South Africa's name for Easter Monday, an extra day of rest and family time following the Easter weekend.",
    "Freedom Day": "Marks South Africa's first democratic elections held in 1994, ending apartheid.",
    "Workers' Day": "Honours workers and the labour movement, held nationwide on 1 May.",
    "Youth Day": "Commemorates the 1976 Soweto uprising and honours the role of young people in the struggle for freedom.",
    "National Women's Day": "Honours the 1956 women's march to the Union Buildings and celebrates the role of women in South African society.",
    "Heritage Day": "Celebrates South Africa's cultural diversity, often marked with traditional food and dress — locally known as 'Braai Day'.",
    "Day of Reconciliation": "Promotes national unity and reconciliation, chosen to mark a date significant to both Afrikaner and Zulu history.",
    "Day of Goodwill": "South Africa's name for Boxing Day, traditionally spent with family and community.",
  },
  IE: {
    "Saint Brigid's Day": "Honours Ireland's patron saint Brigid, added in 2023 as Ireland's first new public holiday in decades.",
    "Saint Patrick's Day": "A celebration of Irish culture and heritage marking the feast day of Ireland's patron saint.",
    "Easter Monday": "The day after Easter Sunday, extending the Easter weekend into a four-day break.",
    "May Day": "Ireland's first-Monday-in-May public holiday, historically tied to spring workers' celebrations.",
    "June Holiday": "A public holiday held on the first Monday of June, one of Ireland's regular \"bank holiday Mondays\".",
    "August Holiday": "A public holiday held on the first Monday of August.",
    "October Holiday": "A public holiday held on the last Monday of October, marking the end of the October school break.",
    "St. Stephen's Day": "Ireland's name for Boxing Day, traditionally marked by the Wren Boys tradition in some areas.",
  },
  PH: {
    "Chinese New Year": "The start of the lunar calendar year, celebrated by the Philippines' large Filipino-Chinese community with family reunions and dragon dances.",
    "Day of Valor": "Commemorates the fall of Bataan during World War II and honours Filipino and American soldiers.",
    "Labour Day": "Honours workers and the labour movement, held nationwide on 1 May.",
    "Independence Day": "Commemorates the Philippines' declaration of independence from Spain in 1898.",
    "Ninoy Aquino Day": "Marks the assassination of opposition leader Benigno 'Ninoy' Aquino Jr. in 1983.",
    "National Heroes Day": "Honours Filipino heroes who fought for the country's independence and freedom.",
    "All Saints' Day Eve": "An extra rest day added before All Saints' Day, when many Filipinos travel to visit family graves.",
    "All Saints' Day": "A Christian holy day honouring all saints, widely observed in the Philippines by visiting family graves.",
    "Bonifacio Day": "Honours Andrés Bonifacio, a founder of the Katipunan revolutionary movement against Spanish rule.",
    "Feast of the Immaculate Conception of Mary": "A major Catholic feast day widely observed with Mass across the Philippines.",
    "Christmas Eve": "The evening before Christmas Day, the centrepiece of the Philippines' famously long Christmas season.",
    "Rizal Day": "Commemorates the execution of national hero Dr. José Rizal in 1896.",
    "Last Day of The Year": "An extra rest day added to close out the calendar year alongside New Year's celebrations.",
  },
  KR: {
    "Lunar New Year": "Korea's biggest family holiday, known as Seollal, observed as a three-day break with ancestral rites and family gatherings.",
    "Independence Movement Day": "Commemorates the 1919 movement against Japanese colonial rule.",
    "Labour Day": "Honours workers and the labour movement, held nationwide on 1 May.",
    "Children's Day": "A day celebrating children's happiness, marked with family outings and gifts.",
    "Buddha's Birthday": "Celebrates the birth of Buddha with lantern parades and temple visits.",
    "Local Election Day": "A nationwide public holiday held so citizens can vote in local government elections.",
    "Memorial Day": "Honours Korean soldiers and civilians who died in war, marked with a moment of silence at 10am.",
    "Constitution Day": "Marks the anniversary of South Korea's constitution, adopted in 1948.",
    "Liberation Day": "Commemorates Korea's liberation from Japanese colonial rule in 1945.",
    "Chuseok": "One of Korea's most important holidays, a three-day harvest festival where families gather to honour their ancestors.",
    "National Foundation Day": "Commemorates the legendary founding of Korea by Dangun in 2333 BC.",
    "Hangul Day": "Celebrates the creation of the Korean alphabet, Hangul, in 1446.",
    "Christmas Day": "The Christian celebration of the birth of Jesus Christ, a public holiday reflecting Korea's sizeable Christian population.",
  },
  CH: {
    "St. Berchtold's Day": "A regional Swiss rest day following New Year's Day, observed in many but not all cantons.",
    "Epiphany": "Marks the visit of the Three Wise Men to the infant Jesus, a cantonal holiday in parts of Switzerland.",
    "Republic Day": "Marks the declaration of the Republic of Neuchâtel in 1848, a holiday unique to that canton.",
    "Saint Joseph's Day": "A Catholic feast honouring Saint Joseph, observed in several Catholic-majority Swiss cantons.",
    "Good Friday": "A Christian observance marking the crucifixion of Jesus Christ, observed in most Swiss cantons.",
    "Näfels procession": "Commemorates a 14th-century battle with a historic procession held only in the canton of Glarus.",
    "Easter Monday": "The day after Easter Sunday, a cantonal holiday across most of Switzerland.",
    "Labour Day": "Honours workers and the labour movement, observed as a cantonal holiday on 1 May.",
    "Ascension Day": "A Christian feast held 40 days after Easter, one of Switzerland's few nationwide public holidays.",
    "Whit Monday": "Falls the day after Pentecost and is kept as a cantonal spring public holiday.",
    "Corpus Christi": "A Catholic feast honouring the Eucharist, observed in Switzerland's Catholic-majority cantons.",
    "Saint Peter and Saint Paul": "A Catholic feast day observed as a cantonal holiday in Ticino.",
    "Swiss National Day": "Celebrates the founding of the Swiss Confederation in 1291 with bonfires and fireworks across the country — Switzerland's only nationwide public holiday.",
    "Assumption of the Virgin Mary": "A Catholic feast celebrating the bodily assumption of the Virgin Mary, observed in Switzerland's Catholic cantons.",
    "Geneva Prayday": "A local Geneva holiday combining a day of prayer with a public holiday, unique to the canton.",
    "Federal Day of Thanksgiving": "A Swiss day of thanks, repentance, and prayer observed nationwide on the third Sunday of September.",
    "Federal Fast Monday": "The Monday following Switzerland's Federal Day of Thanksgiving, observed as a cantonal holiday in Geneva.",
    "All Saints' Day": "A Christian holy day honouring all saints, observed in Switzerland's Catholic-majority cantons.",
    "Immaculate Conception": "A Catholic feast honouring the Virgin Mary, observed in several Swiss cantons.",
    "Christmas Day": "The Christian celebration of the birth of Jesus Christ, Switzerland's other nationwide public holiday.",
    "St. Stephen's Day": "A traditional post-Christmas rest day, observed in most Swiss cantons.",
    "Restoration Day": "Marks the restoration of the Republic of Geneva in 1813, a holiday unique to that canton.",
  },
  BE: {
    "Good Friday": "A Christian observance marking the crucifixion of Jesus Christ, a bank holiday for many Belgian employers.",
    "Easter Sunday": "The most important date in the Christian calendar, celebrating the resurrection of Jesus Christ.",
    "Easter Monday": "The day after Easter Sunday, extending the Easter weekend into a four-day break.",
    "Labour Day": "Honours workers and the labour movement, held nationwide on 1 May.",
    "Ascension Day": "A Christian feast held 40 days after Easter, commemorating the ascension of Jesus into heaven.",
    "Day after Ascension Day": "A bridge day some Belgian employers grant to extend the Ascension long weekend.",
    "Whit Monday": "Falls the day after Pentecost and is kept as an extra spring public holiday.",
    "Belgian National Day": "Marks the 1831 inauguration of Leopold I, Belgium's first king, celebrated with a military parade in Brussels.",
    "Assumption Day": "A Catholic feast celebrating the bodily assumption of the Virgin Mary into heaven.",
    "All Saints' Day": "A Christian holy day honouring all saints, widely observed by visiting family graves.",
    "Armistice Day": "Marks the armistice that ended the First World War on 11 November 1918.",
    "Christmas Day": "The Christian celebration of the birth of Jesus Christ, the biggest family holiday of the year in Belgium.",
    "St. Stephen's Day": "Belgium's name for Boxing Day, a traditional extra day of family time.",
  },
};

module.exports.COUNTRIES = {
  US: {
    name: "the United States", short: "the US", flag: "🇺🇸", demonym: "American",
    intro: "The United States observes eleven federal public holidays each year, though actual days off can vary by state, employer, and industry since there's no single national law requiring paid holiday leave. Federal holidays range from solemn observances like Memorial Day and Veterans Day to celebratory ones like Independence Day and Thanksgiving. Because the U.S. calendar mixes fixed dates with \"floating\" holidays pinned to a specific weekday (like the third Monday in January for MLK Day), the exact date shifts from year to year. Below is the full 2026 federal holiday calendar, including a few notable state-level observances."
  },
  GB: {
    name: "the United Kingdom", short: "the UK", flag: "🇬🇧", demonym: "British",
    intro: "The United Kingdom's public holidays — commonly called \"bank holidays\" — are famously inconsistent across its four nations. England and Wales share one set of dates, Scotland has its own slightly different calendar (with an extra day after New Year's), and Northern Ireland adds two of its own historic observances. Unlike many countries, the UK has no written constitutional right to bank holidays for most workers — entitlement depends on the employment contract. Below is the full 2026 calendar covering all four nations."
  },
  AU: {
    name: "Australia", short: "Australia", flag: "🇦🇺", demonym: "Australian",
    intro: "Australia's public holiday calendar is a patchwork of national dates — like Australia Day, ANZAC Day, and Christmas — layered with state and territory-specific holidays such as Labour Day, King's Birthday, and the Melbourne Cup, which are only observed in certain states. Because holidays are set by each state and territory government, the total number of public holidays a worker gets can differ significantly depending on where in Australia they live. Below is the complete 2026 calendar, including national holidays and the major state observances."
  },
  CA: {
    name: "Canada", short: "Canada", flag: "🇨🇦", demonym: "Canadian",
    intro: "Canada has only a handful of statutory holidays that apply nationwide under federal law, but each province and territory adds several of its own — meaning a worker in Quebec, Ontario, and Newfoundland could all have noticeably different calendars in the same year. Names like \"Family Day,\" \"Civic Holiday,\" and \"Heritage Day\" are often the same date wearing a different regional label. Below is the full 2026 Canadian holiday calendar, covering both nationwide statutory holidays and the major provincial observances."
  },
  DE: {
    name: "Germany", short: "Germany", flag: "🇩🇪", demonym: "German",
    intro: "Germany observes nine public holidays that apply nationwide, but its federal system means individual states (Länder) add extra religious and regional holidays — a legacy of the country's mixed Catholic and Protestant history. Bavaria, for instance, observes several Catholic feast days that aren't public holidays in Berlin or Hamburg. This makes Germany one of the more complex European countries to plan travel or business around. Below is the full 2026 calendar, including nationwide holidays and notable state-level observances."
  },
  FR: {
    name: "France", short: "France", flag: "🇫🇷", demonym: "French",
    intro: "France keeps a relatively short list of eleven public holidays (\"jours fériés\") each year, most rooted in Catholic tradition alongside a handful of secular civic dates like Labour Day and Bastille Day. Unusually, French law doesn't guarantee a day off for most of these holidays that fall on a weekend — there's no automatic \"in-lieu\" Monday off as in many English-speaking countries. Alsace-Moselle is the one region with two extra religious holidays not observed elsewhere in France. Below is the complete 2026 calendar."
  },
  JP: {
    name: "Japan", short: "Japan", flag: "🇯🇵", demonym: "Japanese",
    intro: "Japan has one of the most holiday-dense calendars in the developed world, with sixteen national holidays (\"shukujitsu\") spread across the year — many tied to nature, gratitude, and reflection rather than religion, such as Greenery Day, Mountain Day, and Respect for the Aged Day. Japan also uniquely applies a \"Citizens' Holiday\" rule: if a single weekday falls between two public holidays, it automatically becomes a holiday too. Below is the full 2026 calendar of Japanese national holidays."
  },
  BR: {
    name: "Brazil", short: "Brazil", flag: "🇧🇷", demonym: "Brazilian",
    intro: "Brazil's national holiday calendar blends Catholic feast days with distinctly Brazilian civic dates, including Tiradentes Day and the world-famous Carnival — technically not a federal public holiday everywhere, but treated as one in practice in much of the country. Many Brazilian municipalities and states add their own local holidays (\"pontos facultativos\") on top of the national list, so actual days off can vary widely by city. Below is the complete 2026 national holiday calendar."
  },
  MX: {
    name: "Mexico", short: "Mexico", flag: "🇲🇽", demonym: "Mexican",
    intro: "Mexico observes a compact list of official public holidays under its Federal Labour Law, several of which are deliberately moved to the nearest Monday to create long weekends known as \"puentes.\" The calendar mixes patriotic dates — Independence Day, Revolution Day — with civic tributes to historical figures like Benito Juárez. Notably, widely celebrated cultural dates like Día de los Muertos and Cinco de Mayo are not official nationwide public holidays. Below is the full 2026 calendar."
  },
  ES: {
    name: "Spain", short: "Spain", flag: "🇪🇸", demonym: "Spanish",
    intro: "Spain has one of Europe's most layered holiday systems: a set of national holidays applies everywhere, but each of the seventeen autonomous communities adds its own regional dates — from Catalonia's Diada to Galicia's Letras Galegas day — and individual municipalities can designate two additional local holidays each year. That means the real answer to \"is today a holiday in Spain\" often depends on exactly which region you're in. Below is the full 2026 calendar, covering national holidays and the major regional observances."
  },
  IT: {
    name: "Italy", short: "Italy", flag: "🇮🇹", demonym: "Italian",
    intro: "Italy's public holidays are almost entirely rooted in the Catholic liturgical calendar, blended with a few 20th-century civic dates like Liberation Day and Republic Day that mark the country's transition from monarchy to republic after the Second World War. Beyond the national list, every Italian town also observes its own patron saint's feast day as a local holiday, so the full holiday count in Italy depends heavily on the city. Below is the complete national 2026 calendar."
  },
  NL: {
    name: "the Netherlands", short: "the Netherlands", flag: "🇳🇱", demonym: "Dutch",
    intro: "The Netherlands keeps a short, tightly-defined public holiday calendar of around eleven dates, most tied to Christian tradition and the House of Orange — most famously King's Day, the nationwide street-party holiday celebrating the monarch's birthday. Not all of these are legally guaranteed paid days off for every employee; entitlement often depends on collective labour agreements (CAOs) rather than blanket national law. Below is the full 2026 Dutch public holiday calendar."
  },
  NZ: {
    name: "New Zealand", short: "New Zealand", flag: "🇳🇿", demonym: "New Zealand",
    intro: "New Zealand observes eleven nationwide public holidays, including the culturally significant Waitangi Day and Matariki — the Māori New Year, added as an official public holiday in 2022. On top of the national list, every region also celebrates its own \"provincial anniversary day\" commemorating its founding, meaning the actual number of public holidays a Kiwi gets depends on which province they live in. Below is the complete 2026 calendar, covering both national and regional anniversary holidays."
  },
  SG: {
    name: "Singapore", short: "Singapore", flag: "🇸🇬", demonym: "Singaporean",
    intro: "Singapore's eleven public holidays reflect its multicultural population, combining Christian, Chinese, Malay/Muslim, and Hindu festivals into a single shared calendar — Chinese New Year, Hari Raya Puasa, Deepavali, and Christmas Day all appear alongside secular dates like National Day and Labour Day. When a holiday falls on a Sunday, the next working day is usually observed as a holiday instead. Below is the full 2026 calendar of Singapore's public holidays."
  },
  ZA: {
    name: "South Africa", short: "South Africa", flag: "🇿🇦", demonym: "South African",
    intro: "South Africa's twelve public holidays are unusually rich in modern political history, commemorating the country's transition from apartheid to democracy through dates like Freedom Day, Human Rights Day, and Youth Day. Heritage Day, affectionately known as \"Braai Day,\" celebrates the country's cultural diversity with barbecues nationwide. By law, if a public holiday falls on a Sunday, the following Monday becomes a holiday instead. Below is the complete 2026 calendar."
  },
  IE: {
    name: "Ireland", short: "Ireland", flag: "🇮🇪", demonym: "Irish",
    intro: "Ireland observes ten official public holidays a year, most simply labelled \"[Month] Holiday\" and pinned to the first Monday of that month rather than a fixed date — a system that keeps long weekends predictable throughout the year. St. Brigid's Day, added in 2023, was Ireland's first new public holiday in decades and the first named after a woman. Below is the complete 2026 calendar of Irish public holidays."
  },
  PH: {
    name: "the Philippines", short: "the Philippines", flag: "🇵🇭", demonym: "Filipino",
    intro: "The Philippines has one of the longest public holiday calendars in Asia, split by law into \"regular holidays\" (with mandatory pay premiums) and \"special non-working days,\" and covering everything from Holy Week processions to Chinese New Year and civic tributes to national heroes like Rizal and Bonifacio. The exact dates for several holidays are confirmed annually by presidential proclamation rather than fixed permanently in law. Below is the full 2026 calendar as confirmed for the year."
  },
  KR: {
    name: "South Korea", short: "South Korea", flag: "🇰🇷", demonym: "Korean",
    intro: "South Korea's holiday calendar runs on a dual system, mixing the solar calendar for civic holidays like Constitution Day and Liberation Day with the lunar calendar for its two biggest family holidays, Seollal (Lunar New Year) and Chuseok — both observed as three-day breaks. When a lunar holiday would otherwise clash with another day off, South Korea uses a substitute holiday system to guarantee workers still get the extra day. Below is the complete 2026 calendar."
  },
  CH: {
    name: "Switzerland", short: "Switzerland", flag: "🇨🇭", demonym: "Swiss",
    intro: "Switzerland is a special case: only one day, August 1st (Swiss National Day), is a public holiday in every single canton. Everything else — Epiphany, Corpus Christi, Assumption, even Christmas-adjacent dates — is decided canton by canton, producing 26 slightly different regional calendars across the country. Some cantons observe unique local dates found nowhere else, like Geneva's Jeûne genevois or Glarus's Näfels procession. Below is a combined 2026 calendar showing both the one nationwide holiday and the major cantonal observances."
  },
  BE: {
    name: "Belgium", short: "Belgium", flag: "🇧🇪", demonym: "Belgian",
    intro: "Belgium keeps a straightforward calendar of ten public holidays that apply nationwide across all three regions and language communities — a rarity in a country otherwise known for regional complexity. The calendar leans heavily on Christian feast days (Ascension, Whit Monday, Assumption, All Saints') alongside the Belgian National Day on 21 July, marking the 1831 inauguration of the country's first king. Below is the full 2026 calendar of Belgian public holidays."
  },
};
